version: '3'

services:
  db:
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3306:3306
  viewer:
    image: s0uldrag0n/syslog-viewer-server
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 514:514
      - 3000:3000
